### ISSUE TITLE
No module named distutils

### ISSUE THREAD

**Issue by Pixel-svg** [kishanrajput23/Jarvis-Desktop-Voice-Assistant#10]
I dont know what distutils is but in case it was a python library i tried running pip install distutils but it was not.
You can tell im new to python
I think the readme should be more detailed
![image](https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/172105650/22f1f377-9321-4baa-93a6-21751452320b)

**Comment by kishanrajput23** [comment]
<img width="748" alt="image" src="https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/70385488/81b89fee-ae09-4bcd-872a-d8fcd282fcc2">
<img width="765" alt="image" src="https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/70385488/32d0e0c2-89b6-49c2-9a54-5a94aca8be7d">
<img width="764" alt="image" src="https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/70385488/226030e1-705a-42c5-96d7-c83d3c2b9dd1">
<img width="774" alt="image" src="https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/70385488/6934de21-a1b7-48df-94e3-2eefd33a7e5c">
<img width="759" alt="image" src="https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/70385488/f962a583-51a0-4537-acab-ff867f84af6f">

**Comment by Pixel-svg** [comment]
i installed python from the microsoft store as powershell told me to, does distullise come with that version
