### ISSUE TITLE
Updating ReadMe to set up Virtual Environment

### ISSUE THREAD

**Issue by Ashwamedh-14** [kishanrajput23/Jarvis-Desktop-Voice-Assistant#11]
So, looking through the requirements file I noticed that there are a lot of dependencies that most people probably won't need globally on their system. Instead, they can set up virtual environment so that it does not affect their system globally. I just wanted to update the ReadMe (and .gitignore) so that it can be easier for people to setup by a step-by-step guide.

Also, I was thinking about adding type-hints.

**Comment by kishanrajput23** [comment]
okay go ahead with your idea, I'll check and let you know.

**Comment by kishanrajput23** [comment]
Closing this issue as you're PR successfully got merged.🙌
