### ISSUE TITLE
No module named speech recongition

### ISSUE THREAD

**Issue by Pixel-svg** [kishanrajput23/Jarvis-Desktop-Voice-Assistant#8]
i did every step on the intillation guide but it still returns these problems
![image](https://github.com/kishanrajput23/Jarvis-Desktop-Voice-Assistant/assets/172105650/3ed87b54-144f-45b7-b19a-29d9ce9938c0)
What do i need to install im new to python

**Comment by kishanrajput23** [comment]
# Installing SpeechRecognition in Python

To install a speech recognition library in Python, you typically have a few options. One popular library for speech recognition is SpeechRecognition. Here’s how you can install it:

## Using pip

Open your terminal or command prompt and run:

```bash
pip install SpeechRecognition
```

## Additional dependencies
Depending on your operating system, you might need additional dependencies for SpeechRecognition to work:

### For Windows
You may need to install pyaudio separately. You can do this with:

```bash
pip install pyaudio
```

If you encounter issues, you might need to install pywin32 as well:

```bash
pip install pywin32
```

### For macOS
You might need to install portaudio using brew:

```bash
brew install portaudio
```

Then install pyaudio:

```bash
pip install pyaudio
```


### For Linux
You might need to install portaudio using your package manager (e.g., apt-get, yum, pacman):

```bash
sudo apt-get install portaudio19-dev  # Example for Ubuntu/Debian
```

Then install pyaudio:
```
bash
pip install pyaudio
```

After installing SpeechRecognition and its dependencies, you can start using it in your Python code to recognize speech from various sources such as microphone input or audio files.
